### ISSUE TITLE
ASP.NET Core doesn't work with 3.0 Preview 6

### ISSUE THREAD

**Issue by omajid** [dotnet/source-build#1121]
```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview6-012264
 Commit:    be3f0c1a03
                                                           
Runtime Environment:                                                                                                  
 OS Name:     fedora                                       
 OS Version:  30                                                                                                      
 OS Platform: Linux                                                                                                   
d RID:         fedora.30-x64                               
 Base Path:   /usr/lib64/dotnet/sdk/3.0.100-preview6-012264/                          
                             
Host (useful for support):                                                                                            
  Version: 3.0.0-preview6-27804-01
  Commit:  17dd7897d6                                      
                                                                                                                      
.NET Core SDKs installed:                                                                                             
  3.0.100-preview6-012264 [/usr/lib64/dotnet/sdk]
                             
.NET Core runtimes installed: 
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]
                                                                                                                      
To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download                          
$ dotnet new web
                                                           
Welcome to .NET Core 3.0!  
---------------------                                      
SDK Version: 3.0.100-preview6-012264       
                                                           
----------------      
Explore documentation: https://aka.ms/dotnet-docs          
Report issues and find source on GitHub: https://github.com/dotnet/core                                               
Find out what's new: https://aka.ms/dotnet-whats-new       
Learn about the installed HTTPS developer cert: https://aka.ms/aspnet-core-https                                      
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs                                
Write your first app: https://aka.ms/first-net-core-app    
--------------------------------------------------------------------------------------
Getting ready...             
The template "ASP.NET Core Empty" was created successfully.                                                           
                                                           
Processing post-creation actions...                        
Running 'dotnet restore' on /home/omajid/temp/HelloWeb/HelloWeb.csproj...                                             
  Restore completed in 85.46 ms for /home/omajid/temp/HelloWeb/HelloWeb.csproj.                                       
                                                           
Restore succeeded.           
                                                           
$ sed -i -e 's|.UseStartup|.UseUrls("http://localhost:5000").UseStartup|' Program.cs           
$ dotnet run              
It was not possible to find any compatible framework version                                                          
The specified framework 'Microsoft.AspNetCore.App', version '3.0.0-preview6.19307.2' was not found.                   
  - No frameworks were found.                              
                             
You can resolve the problem by installing the specified framework and/or SDK.                                         
                                                           
The .NET Core frameworks can be found at:                  
  - https://aka.ms/dotnet-download                        
```

**Comment by tmds** [comment]
> It was not possible to find any compatible framework version                                                          
The specified framework 'Microsoft.AspNetCore.App', version '3.0.0-preview6.19307.2' was not found.                   

We are missing support for the Microsoft.AspNetCore.App shared runtime in source-build (https://github.com/dotnet/source-build/issues/375).

CC @natemcmaster

**Comment by crummel** [comment]
@omajid I think this should work now that https://github.com/dotnet/source-build/pull/1144 is in.

**Comment by omajid** [comment]
@crummel Just tried out  commit `ac534e8` and `dotnet new web && dotnet run` still fails:

<details>
<summary>Here's what I did:</summary>

```
$ mkdir HelloWeb
$ cd HelloWeb/
$ clean-dotnet-cache                                                                           
+ rm -rf /home/omajid/.aspnet /home/omajid/.dotnet/ /home/omajid/.mono/ /home/omajid/.nuget/ /home/omajid/.local/share/NuGet /home/omajid/.templateengine                                                                                   
+ rm -rf /tmp/NuGet /tmp/NuGetScratch /tmp/.NETCoreApp,Version=v1.0.AssemblyAttributes.cs /tmp/.NETCoreApp,Version=v1.1.AssemblyAttributes.cs /tmp/.NETCoreApp,Version=v2.0.AssemblyAttributes.cs /tmp/.NETCoreApp,Version=v2.0.AssemblyAttributes.fs /tmp/.NETCoreApp,Version=v2.1.AssemblyAttributes.cs /tmp/.NETCoreApp,Version=v2.2.AssemblyAttributes.cs /tmp/.NETCoreApp,Version=v4.0.AssemblyAttributes.cs /tmp/.NETStandard,Version=v1.0.AssemblyAttributes.cs /tmp/.NETStandard,Version=v1.3.AssemblyAttributes.cs /tmp/.NETStandard,Version=v1.4.AssemblyAttributes.cs /tmp/.NETStandard,Version=v1.5.AssemblyAttributes.cs /tmp/.NETStandard,Version=v1.6.AssemblyAttributes.cs /tmp/.NETStandard,Version=v1.6.AssemblyAttributes.fs /tmp/.NETStandard,Version=v2.0.AssemblyAttributes.cs /tmp/.NETStandard,Version=v2.0.AssemblyAttributes.fs 
/tmp/.dotnet /tmp/clr-debug-pipe-13133-53372506-in /tmp/clr-debug-pipe-13133-53372506-out /tmp/Razor-Server /tmp/CoreFxPipe_omajid.F.0hBHIlUWJ3 /tmp/CoreFxPipe_omajid.F.CepdhZ0Wm7sJi0LtoQIDlA6w1 /tmp/CoreFxPipe_omajid.F.SgjyFz8RjICdlqNg6t98YixkR /tmp/CoreFxPipe_omajid.F.TJZtrL98yAZ89QoXNF6RzYTU+ /tmp/CoreFxPipe_omajid.F.UJn79uW29Z0JiIIkI76eHpezW /tmp/CoreFxPipe_omajid.F.Yf+HPYLkwM /tmp/CoreFxPipe_omajid.IHsqxAz3WUpqmXmse7wqNz16U /tmp/VBCSCompiler /tmp/.NETFramework,Version=v4.0.AssemblyAttributes.cs /tmp/.NETFramework,Version=v4.6.AssemblyAttributes.cs /tmp/.NETFramework,Version=v4.7.2.AssemblyAttributes.cs /tmp/dotnet.c1mBmHq2z /tmp/dotnet.fazOyIzF8 /tmp/dotnet.GkAhVsYps /tmp/dotnet.hYI2qqxDe /tmp/dotnet.QYbBk38LJ /tmp/dotnet.SDl8Q1OV3 /tmp/dotnet.Vy6Djb75k

$ ~/temp/dotnet-sdk-3.0-preview8/dotnet --info                                                 
.NET Core SDK (reflecting any global.json):                
 Version:   3.0.100-preview8-013656                        
 Commit:    8bf06ffc8d
                                                           
Runtime Environment:                                       
 OS Name:     fedora                                       
 OS Version:  29           
 OS Platform: Linux                                                                                                   
 RID:         fedora.29-x64                                                                                           
 Base Path:   /home/omajid/temp/dotnet-sdk-3.0-preview8/sdk/3.0.100-preview8-013656/                                  
                                                                                                                      
Host (useful for support):                                                                                            
  Version: 3.0.0-preview8-28405-07                                                                                    
  Commit:  ac534e82d1                                                                                                 
                                                                                                                      
.NET Core SDKs installed:                                                                                             
  3.0.100-preview8-013656 [/home/omajid/temp/dotnet-sdk-3.0-preview8/sdk]                                             
                                                                                                                      
.NET Core runtimes installed:                                                                                         
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [/home/omajid/temp/dotnet-sdk-3.0-preview8/shared/Microsoft.AspNetCore.App]                                                                                                               
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [/home/omajid/temp/dotnet-sdk-3.0-preview8/shared/Microsoft.NETCore.App]                                                                                                                    
                                                                                                                      
To install additional .NET Core runtimes or SDKs:          
  https://aka.ms/dotnet-download                                                                                      

$ ~/temp/dotnet-sdk-3.0-preview8/dotnet new web         
                                                           
Welcome to .NET Core 3.0!                                  
--------------------- 
SDK Version: 3.0.100-preview8-013656                                                                                  
                                                                                                                      
Telemetry                                                                                                             
---------                                                                                                             
The .NET Core tools collect usage data in order to help us improve your experience. The data is anonymous. It is colle
cted by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTO
UT environment variable to '1' or 'true' using your favorite shell.                 
                                                           
Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry                                    
                                                           
----------------
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Find out what's new: https://aka.ms/dotnet-whats-new
Learn about the installed HTTPS developer cert: https://aka.ms/aspnet-core-https
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs
Write your first app: https://aka.ms/first-net-core-app
--------------------------------------------------------------------------------------
Getting ready...
The template "ASP.NET Core Empty" was created successfully. 

Processing post-creation actions...
Running 'dotnet restore' on /home/omajid/temp/HelloWeb/HelloWeb.csproj...
  Restore completed in 72.53 ms for /home/omajid/temp/HelloWeb/HelloWeb.csproj.

Restore succeeded.

$ ~/temp/dotnet-sdk-3.0-preview8/dotnet run
It was not possible to find any compatible framework version
The specified framework 'Microsoft.AspNetCore.App', version '3.0.0-preview8.19405.7' was not found.
  - Check application dependencies and target a framework version installed at:
      /usr/lib64/dotnet
  - Installing .NET Core prerequisites might help resolve this problem:
      https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The .NET Core framework and SDK can be installed from:
      https://aka.ms/dotnet-download
```

</details>

**Comment by crummel** [comment]
Hmm, sorry about that.  Let me try this on a clean machine.

**Comment by omajid** [comment]
@crummel Oh, nevermind.

See that `/usr/lib64/dotnet` in the output? I had `DOTNET_ROOT` set and that screws things up :(
